name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main


jobs:
  build-and-push:
    name: Build & Push Docker Image
    environment: hml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker Auth for Artifact Registry
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}-registry/${{ vars.SERVICE_NAME }}:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}-registry/${{ vars.SERVICE_NAME }}:${{ github.sha }}

  deploy-hml:
    name: Deploy to HML
    needs: build-and-push
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main'
    environment: hml
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="prefix=${{ vars.SERVICE_NAME }}-hml" -backend-config="bucket=${{ vars.PROJECT_ID }}-tfstate"

      - name: Terraform Apply HML
        run: terraform apply -auto-approve -var="environment=hml" -var="project_id=${{ vars.PROJECT_ID }}" -var="image_tag=${{ github.sha }}"

  deploy-prod:
    name: Deploy to PRD
    needs: deploy-hml
    if: github.ref == 'refs/heads/main'
    environment: prd
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -backend-config="prefix=${{ vars.SERVICE_NAME }}-prd" -backend-config="bucket=${{ vars.PROJECT_ID }}-tfstate"

      - name: Terraform Apply PRD
        run: terraform apply -auto-approve -var="environment=prd" -var="project_id=${{ vars.PROJECT_ID }}" -var="image_tag=${{ github.sha }}"
